# Generated by Django 3.2.11 on 2022-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('Agreement_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Agreement', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Agreement',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('Author_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Author', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='AuthorID',
            fields=[
                ('AuthorID_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Author', models.CharField(default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'AuthorID',
            },
        ),
        migrations.CreateModel(
            name='Dependent_Variable',
            fields=[
                ('Dependent_Variable_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantitative_ID', models.IntegerField(default=0, null=True)),
                ('Is_categorical', models.BooleanField(default=0, null=True)),
                ('DV_name', models.CharField(default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Dependent_Variable',
            },
        ),
        migrations.CreateModel(
            name='Descriptive_Statics',
            fields=[
                ('Descriptive_Statics_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Descriptive_Statics', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Descriptive_Statics',
            },
        ),
        migrations.CreateModel(
            name='DV_Level',
            fields=[
                ('DV_Level_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Dependent_Variable_ID', models.IntegerField(default=0, null=True)),
                ('Name', models.CharField(default='', max_length=100, null=True)),
            ],
            options={
                'db_table': 'DV_Level',
            },
        ),
        migrations.CreateModel(
            name='Independent_Variable',
            fields=[
                ('Independent_Variable_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantitative_ID', models.IntegerField(default=0, null=True)),
                ('Is_categorical', models.BooleanField(default=0, null=True)),
                ('IV_name', models.CharField(default='', max_length=100, null=True)),
                ('P_value_sign', models.CharField(default='', max_length=100, null=True)),
                ('P_value', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('CIl', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('CIr', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Coef', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Exp', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('OR', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Estimates', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('SE', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('T', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Degrees_of_Freedom', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('WU', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('xf2', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'Independent_Variable',
            },
        ),
        migrations.CreateModel(
            name='IV_Level',
            fields=[
                ('IV_Level_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Independent_Variable_ID', models.IntegerField(default=0, null=True)),
                ('Name', models.CharField(default='', max_length=100, null=True)),
                ('Is_baseline', models.BooleanField(default=0, null=True)),
                ('P_value_sign', models.CharField(default='', max_length=100, null=True)),
                ('P_value', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('CIl', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('CIr', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Coef', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('OR', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Estimates', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Exp', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('SE', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'IV_Level',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('Main_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=100, null=True)),
                ('Research', models.CharField(default='', max_length=100, null=True)),
                ('Year', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'Main',
            },
        ),
        migrations.CreateModel(
            name='Qualitative',
            fields=[
                ('Qualitative_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Data_Analysis_Method', models.CharField(default=0, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Qualitative',
            },
        ),
        migrations.CreateModel(
            name='Quantitative',
            fields=[
                ('Quantitative_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Analysis_Method', models.CharField(default='', max_length=100, null=True)),
                ('P_value_sign', models.CharField(default='', max_length=100, null=True)),
                ('P_value', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('OR', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('WU', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('T', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Degrees_of_Freedom', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('xf2', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('R', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('df', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('CIl', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('CIr', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
                ('Cor_P_sign', models.CharField(default='', max_length=100, null=True)),
                ('Cor_P', models.DecimalField(decimal_places=4, default=0, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'Quantitative',
            },
        ),
        migrations.CreateModel(
            name='Research_Questions',
            fields=[
                ('Research_Questions_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Research_Questions', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Research_Questions',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('Sample_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Quantitative_ID', models.IntegerField(default=0, null=True)),
                ('Qualitative_ID', models.IntegerField(default=0, null=True)),
                ('Sample_Type', models.CharField(default='', max_length=100, null=True)),
                ('Sample_Size', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'Sample',
            },
        ),
        migrations.CreateModel(
            name='Study_Methods',
            fields=[
                ('Study_Methods_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Paper_ID', models.IntegerField(default=0, null=True)),
                ('Study_Methods', models.CharField(default='', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Study_Methods',
            },
        ),
    ]
